# Generated by Django 5.0.6 on 2024-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_descripcion_detalleproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(default='0GB', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='pantalla',
            field=models.CharField(default='0"', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='procesador',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='ram',
            field=models.CharField(default='0GB', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='DetalleProducto',
        ),
    ]
