# Generated by Django 5.0.6 on 2024-07-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='pantalla',
        ),
        migrations.AddField(
            model_name='producto',
            name='capacidad_bateria',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño_pantalla',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='procesador',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ram',
            field=models.CharField(default='', max_length=80),
        ),
    ]
