# Generated by Django 5.0.6 on 2025-05-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_producto_pantalla_producto_capacidad_bateria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(default='No Registrado', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='capacidad_bateria',
            field=models.CharField(default='No Registrado', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(default='No Registrado', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='procesador',
            field=models.CharField(default='No Registrado', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ram',
            field=models.CharField(default='No Registrado', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamaño_pantalla',
            field=models.CharField(default='No Registrado', max_length=80),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('BODEGUERO', 'Bodeguero'), ('CONTADOR', 'Contador')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
