# Generated by Django 5.0.6 on 2025-05-10 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_almacenamiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('RECHAZADO', 'Rechazado por el vendedor'), ('ACEPTADO', 'Aprobado por el vendedor'), ('EN_ESPERA_PAGO', 'Esperando pago del cliente'), ('PAGO_CONFIRMADO', 'Pago confirmado por contador'), ('LISTO_DESPACHO', 'Cliente eligió despacho/retiro'), ('ENTREGADO', 'Preparado y entregado por bodeguero'), ('VENTA_FINALIZADA', 'Venta completada')], default='PENDIENTE', max_length=30)),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_entrega', models.CharField(blank=True, max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido')),
            ],
        ),
    ]
