# Generated by Django 5.0.6 on 2025-05-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='almacenamiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='capacidad_bateria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='procesador',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tamaño_pantalla',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('RECHAZADO', 'Rechazado por el vendedor'), ('ACEPTADO', 'Aprobado por el vendedor'), ('EN_ESPERA_PAGO', 'Esperando pago del cliente'), ('LISTO_PAGO', 'Pedido listo para pago'), ('PAGO_CONFIRMADO', 'Pago confirmado por contador'), ('LISTO_DESPACHO', 'Cliente eligió despacho/retiro'), ('ENTREGADO', 'Preparado y entregado por bodeguero'), ('VENTA_FINALIZADA', 'Venta completada')], default='PENDIENTE', max_length=30),
        ),
    ]
